# Generated by Django 3.0.7 on 2020-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='productingredient',
            name='unit',
            field=models.CharField(choices=[('ml', 'milliliter'), ('gr', 'gram'), ('pcs', 'pieces')], default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
