# Generated by Django 3.0.7 on 2020-07-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200707_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Product'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='base_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_recipes', to='data.Recipe'),
        ),
    ]
