# Generated by Django 3.0.8 on 2020-08-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200802_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='unit',
            field=models.CharField(choices=[('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(choices=[('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Product')),
            ],
        ),
    ]
