# Generated by Django 3.1.2 on 2020-12-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20201025_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='unit',
            field=models.CharField(choices=[('-', '-'), ('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='unit',
            field=models.CharField(choices=[('-', '-'), ('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='unit',
            field=models.CharField(choices=[('-', '-'), ('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sessionproduct',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sessionproduct',
            name='unit',
            field=models.CharField(choices=[('-', '-'), ('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionrecipe',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='from_unit',
            field=models.CharField(choices=[('-', '-'), ('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='to_unit',
            field=models.CharField(choices=[('-', '-'), ('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='mL', max_length=5),
        ),
    ]
