# Generated by Django 3.0.8 on 2020-08-15 14:42

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200729_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='image',
            field=models.ImageField(height_field='height', upload_to=common.models.model_directory_path, width_field='width'),
        ),
    ]
