# Generated by Django 3.1 on 2020-08-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_unitconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='scale',
            field=models.FloatField(),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type', 'from_unit', 'to_unit'), name='unique_conversions'),
        ),
    ]
