# Generated by Django 3.1 on 2020-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200817_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='to_unit',
            field=models.CharField(choices=[('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='mL', max_length=5),
        ),
    ]
