# Generated by Django 3.1 on 2020-10-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_smallimagetag_squashed_0010_auto_20201004_1846"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="imagetag", name="content_type",),
                migrations.RemoveField(
                    model_name="unitconversion", name="content_type",
                ),
                migrations.DeleteModel(name="AlternateImageTag",),
                migrations.DeleteModel(name="ImageTag",),
                migrations.DeleteModel(name="UnitConversion",),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="AlternateImageTag", table="data_alternateimagetag",
                ),
                migrations.AlterModelTable(name="ImageTag", table="data_imagetag",),
                migrations.AlterModelTable(
                    name="UnitConversion", table="data_unitconversion",
                ),
            ],
        ),
    ]
