# Generated by Django 3.0.7 on 2020-07-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0006_auto_20200712_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('session_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Recipe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baking.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='baking.Session')),
                ('source_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='recipes',
            field=models.ManyToManyField(related_name='sessions', through='baking.SessionRecipe', to='data.Recipe'),
        ),
    ]
