# Generated by Django 3.0.7 on 2020-07-14 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0002_auto_20200712_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
