# Generated by Django 3.0.7 on 2020-07-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0003_auto_20200714_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecipe',
            name='sort_key',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
