# Generated by Django 3.0.7 on 2020-07-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0004_auto_20200720_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_date', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='sessionrecipe',
            options={'ordering': ['sort_key']},
        ),
    ]
