# Generated by Django 3.0.7 on 2020-07-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200721_1659'),
        ('baking', '0005_auto_20200721_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('sort_key', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='baking.Session')),
            ],
            options={
                'ordering': ['sort_key'],
            },
        ),
        migrations.DeleteModel(
            name='SessionIngredients',
        ),
        migrations.AddField(
            model_name='session',
            name='products',
            field=models.ManyToManyField(related_name='sessions', through='baking.SessionProduct', to='data.Product'),
        ),
    ]
