# Generated by Django 3.0.7 on 2020-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0006_auto_20200721_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecipe',
            name='unit',
            field=models.CharField(choices=[('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'pieces')], default='pcs', max_length=5),
        ),
    ]
