# Generated by Django 3.0.7 on 2020-07-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0007_sessionrecipe_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrecipe',
            name='unit',
        ),
        migrations.AddField(
            model_name='sessionproduct',
            name='unit',
            field=models.CharField(choices=[('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'pieces')], default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='sessionrecipe',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recipes', to='baking.Session'),
        ),
    ]
