# Generated by Django 3.0.8 on 2020-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0008_auto_20200721_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionproduct',
            name='unit',
            field=models.CharField(choices=[('mL', 'milliliter'), ('g', 'gram'), ('pcs', 'stuk'), ('el', 'eetlepel'), ('tl', 'theelepel')], default='g', max_length=5),
        ),
    ]
