# Generated by Django 3.0.8 on 2020-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0009_auto_20200804_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='recipe_description',
            field=models.TextField(blank=True),
        ),
    ]
